### ISSUE TITLE
Migrate library for improved Deno support

### ISSUE THREAD

**Issue by aaronhuggins** [aaronhuggins/cbor-redux#17]
In preparation for some Deno prod work in a private project, I'm prepping for a v1.0 release. The goal is to heavily simplify the codebase, improve the deployment process, and reduce load to maintain the library.

- [x] Release v0.4.0 on npm #10
- [x] Merge all outstanding PRs #13
- [x] Use inclusive branch naming, i.e. `main`
- [x] Remove all node-specific configuration
- [x] Clean up codebase for vanilla Deno support #15
- [x] Add Deno test suite
- [x] Add support for encoding numeric keys in maps #16
- [x] Add Deno config
- [x] Add support for [Deno to Node Tool](https://github.com/denoland/dnt)
- [x] Forbid duplicate map keys during decoding #11
- [x] Add Github CI/CD pipeline
- [x] Deploy v1 to Deno.Land/x and NPM #17

**Comment by aaronhuggins** [comment]
For interested parties, [here's how the docs are shaping up](https://doc.deno.land/https://deno.land/x/cbor_redux@1.0.0-2/mod.ts).

Though the docs will be generated via doc.deno.land, they are applicable to Node/Deno/Web since it's literally all the same code.
